<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>InventorAutosave</RootNamespace>
    <AssemblyName>InventorAutosave</AssemblyName>
    <Version Condition="'$(Version)' == ''">0.1.0</Version>
    <InventorVersion>2026</InventorVersion>
    <CopyInventorFiles>false</CopyInventorFiles>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <EnableComHosting>true</EnableComHosting>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <Reference Include="Autodesk.Inventor.Interop">
      <HintPath>$(NuGetPackageRoot)/autodesk.inventor.sdk/1.0.3/lib/native/2026/inventor/Autodesk.Inventor.Interop.dll</HintPath>
      <Private>false</Private>
      <EmbedInteropTypes>false</EmbedInteropTypes>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autodesk.Inventor.Sdk" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="Autodesk.Inventor.Sdk" Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\InventorAutosave.Core\\InventorAutosave.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="InventorAutosave.Inventor.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="SetGitTag" BeforeTargets="BeforeBuild">
    <Exec Command="git describe --always" ConsoleToMSBuild="True" StandardOutputImportance="Low" ContinueOnError="true">
      <Output PropertyName="GitTag" TaskParameter="ConsoleOutput" />
    </Exec>
    <PropertyGroup>
      <GitTag>$([System.String]::Copy('$(GitTag)').Trim())</GitTag>
      <InformationalVersion Condition="'$(GitTag)' != ''">$(Version)+$(GitTag)</InformationalVersion>
    </PropertyGroup>
    <ItemGroup Condition="'$(GitTag)' != ''">
      <AssemblyMetadata Include="GitTag" Value="$(GitTag)" />
    </ItemGroup>
  </Target>
</Project>
